### ISSUE TITLE
Tennants/integrations info in repo

### ISSUE THREAD

**Issue by themotka** [d-kv/signer#19]
![bundle_id/gorm.go](https://github.com/d-kv/signer/assets/74961598/043d3b2c-64da-4dc1-a702-defbe5c28146)
![commands.go](https://github.com/d-kv/signer/assets/74961598/28235d4c-dc25-40c7-992f-89f2ba183c6a)

На примере bunleId, у нас в бд у него зависимость с интеграцией, соответственно при создании нужно найти интеграцию по id, который мы таскаем в очереди. Открывается вопрос, какой сценарий занесения в бд информации о теннантах и интеграциях.

**Comment by maksmolchdmitr** [comment]
Как Дима и говорил - это будут делать человеки ответственные за это

**Comment by themotka** [comment]
Это и был вопрос к созвону, не подразумевал ответа здесь
