### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by themotka** [d-kv/signer#6]
https://github.com/d-kv/signer/blob/51a874bba14004c86c50eb34e83d7d9d85e5f38d/command-executor/internal/repo/commands_postgres.go#L16-L46
Одни и те же структура и метод в command-executor/internal/repo/commands_postgres.go и command-executor/internal/repo/domain_repo.go

**Comment by maksmolchdmitr** [comment]
Сделаю общую кодовую базу для работы с postges бд

**Comment by maksmolchdmitr** [comment]
Не сделаю
